Models/ErrorViewModel.cs
using System;

namespace DataKendaraan.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Kendaraan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DataKendaraan.Models
{
    public class Kendaraan
    {
        [Key]
        public  string NoRegistrasi { get; set; }

        [Required(ErrorMessage = "Silahkan Masukkan Nama!")]
        public string NamaPemilik { get; set; }

        [Required(ErrorMessage = "Silahkan Masukkan Alamat!")]
        public string Alamat { get; set; }

        [Required(ErrorMessage = "Silahkan Masukkan Merk!")]
        public string Merk { get; set; }

        [Required(ErrorMessage = "Silahkan Masukkan Tahun Pembuatan")]
        public int TahunPembuatan { get; set; }

        [Required(ErrorMessage = "Silahkan Masukkan Kapasitas!")]
        public int Kapasitas { get; set; }

        [Required(ErrorMessage = "Silahkan Masukkan Warna Kendaraan!")]
        public string Warna { get; set; }

        [Required(ErrorMessage = "Silahkan Pilih Bahan Bakar!")]
        public string BahanBakar { get; set; }

    }
}

Controllers/Api/KendaraanController.cs
using DataKendaraan.Models;
using DataKendaraan.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DataKendaraan.Api.Controllers
{
    [Route("api/[controller]")]
    public class KendaraanController : Controller
    {
        private readonly KendaraanRepository _repo;
        public KendaraanController(KendaraanRepository repository)
        {
            _repo = repository;
        }

        [HttpGet]
        [Route("GetKendaraan")]
        public IActionResult GetKendaraan()
        {
            var data = _repo.GetKendaraan().ToList();

            return Ok(data);
        }

        [HttpPost]
        [Route("PostKendaraan")]
        public async Task<IActionResult> PostKendaraan(Kendaraan kendaraan)
        {
            if (ModelState.IsValid)
            {
                await _repo.CreateKendaraan(kendaraan);

                return Ok(kendaraan);
            }

            return NotFound();
        }

        [HttpGet]
        [Route("DetailKendaraan/{noReg}")]
        public IActionResult DetailKendaraan(string noReg)
        {
            var val = _repo.GetKendaraanDetail(noReg);
            if (val != null)
            {
                return Ok(val);
            }
            return NotFound();

        }

        [HttpDelete]
        [Route("DeleteKendaraan/{noReg}")]
        public async Task<IActionResult> DeleteKendaraan(string noReg)
        {
            var getData = _repo.GetKendaraanDetail(noReg);

            if (getData != null)
            {
                await _repo.DeleteKendaraan(getData);
                return Ok(getData);
            }

            return NotFound();
        }

        [HttpPut]
        [Route("PutKendaraan/{noReg}")]
        public async Task<IActionResult> EditKendaraan(string noReg, Kendaraan kendaraan)
        {
            if (ModelState.IsValid)
            {
                var getData = _repo.GetKendaraanDetail(kendaraan.NoRegistrasi);

                if (getData != null)
                {
                    await _repo.EditKendaraan(kendaraan);

                    return Ok(kendaraan);
                }
            }
            return NotFound();
        }

        [HttpGet]
        [Route("SearchKendaraan")]
        public IActionResult SearchKendaraan(Kendaraan kendaraan)
        {
            var getData = _repo.Filter(kendaraan);

            if (getData != null)
            {
                return Ok(getData);
            }

            return NotFound();
        }
    }
}

Controllers/HomeController.cs
using DataKendaraan.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DataKendaraan.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/KendaraanController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DataKendaraan.Controllers
{
    public class KendaraanController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult TambahData()
        {
            return View();
        }

        public IActionResult Detail()
        {
            return View();
        }

        public IActionResult Edit()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Kendaraan/Detail.cshtml
<div class="container border rounded-sm border-dark mt-3 p-3">
    <div>
        <h1>Tambah Data Kendaraan</h1>
    </div>
    <div class="p-2">
        <form id="form-edit">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="no-reg">No Registrasi</label>
                    <input type="text" class="form-control" id="no-reg" readonly>
                </div>
                <div class="form-group col-md-6">
                    <label for="tahun-pembuatan">Tahun Pembuatan</label>
                    <input type="text" class="form-control" id="tahun-pembuatan" readonly>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="nama-pemilik">Nama Pemilik</label>
                    <input type="text" class="form-control" id="nama-pemilik" readonly>
                </div>
                <div class="form-group col-md-6">
                    <label for="kapasitas">Kapasitas Silinder</label>
                    <input type="text" class="form-control" id="kapasitas" readonly>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="merk-kendaraan">Merk Kendaraan</label>
                    <input type="text" class="form-control" id="merk-kendaraan" readonly>
                </div>
                <div class="form-group col-md-6">
                    <label for="warna">Warna Kendaraan</label>
                    <input type="text" class="form-control" id="warna" readonly>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="alamat">Alamat Pemilik Kendaraan</label>
                    <textarea class="form-control" id="alamat" rows="3" name="alamat" readonly></textarea>
                </div>
                <div class="form-group col-md-6">
                    <label for="bahan-bakar">Bahan Bakar</label>
                    <input type="text" class="form-control" id="bahan-bakar" name="bahanBakar" readonly>
                </div>
            </div>
            <div class="mt-2">
                <button type="submit" class="btn btn-dark" asp-controller="Kendaraan" asp-action="Index">Kembali</button>
            </div>
        </form>
    </div>
</div>

@section Scripts{

    <script>
        $(document).ready(function () {
            const url = new URLSearchParams(document.location.search);
            const id = url.get('id');

            const endPoint = `https://localhost:44330/api/kendaraan/detailkendaraan/${id}`;

            $.ajax({
                url: endPoint,
                method: "GET",
                success: function (res) {
                    $("#no-reg").val(res.noRegistrasi);
                    $("#tahun-pembuatan").val(res.tahunPembuatan);
                    $("#nama-pemilik").val(res.namaPemilik);
                    $("#kapasitas").val(res.kapasitas);
                    $("#merk-kendaraan").val(res.merk);
                    $("#warna").val(res.warna);
                    $("#alamat").val(res.alamat);
                    $("#bahan-bakar").val(res.bahanBakar);
                },
                error: function (err) {
                    console.log(err);
                }
            });
        });

        




    </script>
}

Views/Kendaraan/Edit.cshtml
<div class="container border rounded-sm border-dark mt-3 p-3">
    <div>
        <h1>Tambah Data Kendaraan</h1>
    </div>
    <div class="p-2">
        <form method="/" id="form-edit">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="no-reg">No Registrasi</label>
                    <input type="text" class="form-control" id="no-reg" name="noReg" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="tahun-pembuatan">Tahun Pembuatan</label>
                    <input type="text" class="form-control" id="tahun-pembuatan" name="thnPembuatan" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="nama-pemilik">Nama Pemilik</label>
                    <input type="text" class="form-control" id="nama-pemilik" name="namaPemilik" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="kapasitas">Kapasitas Silinder</label>
                    <input type="text" class="form-control" id="kapasitas" name="kapasitas" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="merk-kendaraan">Merk Kendaraan</label>
                    <input type="text" class="form-control" id="merk-kendaraan" name="merk" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="warna">Warna Kendaraan</label>
                    <select class="form-control" id="warna" name="warna" required>
                        
                    </select>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="alamat">Alamat Pemilik Kendaraan</label>
                    <textarea class="form-control" id="alamat" rows="3" name="alamat" required></textarea>
                </div>
                <div class="form-group col-md-6">
                    <label for="bahan-bakar">Bahan Bakar</label>
                    <input type="text" class="form-control" id="bahan-bakar" name="bahanBakar" required>
                </div>
            </div>
            <div class="mt-2">
                <button type="submit" class="btn btn-primary">Simpan</button>
                <a class="btn btn-dark" asp-controller="Kendaraan" asp-action="Index">Kembali</a>
            </div>
        </form>
    </div>
</div>

@section Scripts{ 

    <script>

        $(document).ready(function () {
            const url = new URLSearchParams(document.location.search);
            const id = url.get('id');

            const endPoint = `https://localhost:44330/api/kendaraan/detailkendaraan/${id}`;

            $.ajax({
                url: endPoint,
                method: "GET",
                success: function (res) {
                    $("#no-reg").val(res.noRegistrasi);
                    $("#tahun-pembuatan").val(res.tahunPembuatan);
                    $("#nama-pemilik").val(res.namaPemilik);
                    $("#kapasitas").val(res.kapasitas);
                    $("#merk-kendaraan").val(res.merk);
                    $("#warna").val(res.warna);
                    $("#alamat").val(res.alamat);
                    $("#bahan-bakar").val(res.bahanBakar);


                    let warna = ['Merah', 'Hitam', 'Biru', 'Abu-Abu'];

                    let optionsTag = warna.reduce((x, y) => x + `<option value="${y}" ${ y === res.warna ? 'selected' : '' }>${y}</option>`, '');
                    $('#warna').html(optionsTag);
                },
                error: function (err) {
                    console.log(err);
                }
            });
        });

        $("#form-edit").submit((e) => {
            e.preventDefault();

            const { noReg, thnPembuatan, namaPemilik, kapasitas, merk, warna, alamat, bahanBakar } = e.target;

            $.ajax({
                method: "PUT",
                url: `/api/Kendaraan/putkendaraan/${noReg.value}`,
                data: {
                    noRegistrasi: noReg.value,
                    namaPemilik: namaPemilik.value,
                    alamat: alamat.value,
                    merk: merk.value,
                    tahunPembuatan: thnPembuatan.value,
                    kapasitas: kapasitas.value,
                    warna: warna.value,
                    bahanBakar: bahanBakar.value,
                },
                success: function (respon) {
                    alert(`Data Berhasil Diedit`);
                    location.href = `/Kendaraan/Detail?id=${noReg.value}`;
                },
                error: function (err) {
                    alert("Error Server!");
                }
            })
        })

    </script>

}

Views/Kendaraan/Index.cshtml
@{
    Layout = "_Layout";
}

<div class="container-fluid border rounded-sm border-dark  p-3 mt-3" style="border: 2px solid;">
    <div>
        <h1>Aplikasi Data Kendaraan</h1>
    </div>
    <div class="m-lg-2 mt-lg-4">
        <form class="" id="form-search">
            <div class="w-auto" style="padding: 20px; background: #f5d5c1; ">
                <div class="form-group">
                    <label for="input-noreg">No Registrasi</label>
                    <input type="text" class="form-control w-25" id="input-noreg" name="noReg" placeholder="Masukkan No Registrasi">
                </div>
                <div class="form-group">
                    <label for="input-nama">Nama Pemilik</label>
                    <input type="text" class="form-control w-25" id="input-nama" name="nama" placeholder="Nama Pemilik">
                </div>
            </div>
        </form>
        <div class="form-group d-flex justify-content-end p-1 mt-1" style="gap:1rem;">
            <button class="btn btn-primary" id="btn-search">Search</button>
            <a class="btn btn-primary" asp-controller="Kendaraan" asp-action="TambahData">Add</a>
        </div>
    </div>

    <div class="m-lg-2 mt-lg-2">
        <div class="table table-responsive">
            <table class="table table-bordered table-hover table-striped table-sm text-center" id="tabel-employee">
                <thead class="table table-primary ">
                    <tr>
                        <th scope="col">No</th>
                        <th>No Registrasi</th>
                        <th>Nama Pemilik</th>
                        <th>Merk Kendaraan</th>
                        <th>Tahun Pembuatan</th>
                        <th>Kapasitas</th>
                        <th>Warna</th>
                        <th>Bahan Bakar</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody class="table align-middle" id="row-data">
                </tbody>
            </table>
        </div>
    </div>

    <!-- Button trigger modal -->
    @*<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Launch demo modal
    </button>*@

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modal-body">
                    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                    <button type="button" class="btn btn-primary" id="konfirmasi">Ok</button>
                </div>
            </div>
        </div>
    </div>

</div>



@section Scripts{ 

    <script>

        

    </script>

}

Views/Kendaraan/TambahData.cshtml
<div class="container border rounded-sm border-dark mt-3 p-3">
    <div>
        <h1>Tambah Data Kendaraan</h1>
    </div>
    <div class="p-2">
        <form id="form-add">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="no-reg">No Registrasi</label>
                    <input type="text" class="form-control" id="no-reg" name="noReg" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="tahun-pembuatan">Tahun Pembuatan</label>
                    <input type="text" class="form-control" id="tahun-pembuatan" name="thnPembuatan" placeholder="range: 2002 - 2022"
                           onkeypress="return isNumber(event)" 
                           oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);" maxlength = "4" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="nama-pemilik">Nama Pemilik</label>
                    <input type="text" class="form-control" id="nama-pemilik" name="namaPemilik" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="kapasitas">Kapasitas Silinder</label>
                    <input type="text" class="form-control" id="kapasitas" name="kapasitas" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="merk-kendaraan">Merk Kendaraan</label>
                    <input type="text" class="form-control" id="merk-kendaraan" name="merk" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="warna">Warna Kendaraan</label>
                    <select class="form-control" id="warna" name="warna" required>
                        <option value="Merah">Merah</option>
                        <option value="Hitam">Hitam</option>
                        <option value="Biru">Biru</option>
                        <option value="Abu-Abu">Abu-Abu</option>
                    </select>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="alamat">Alamat Pemilik Kendaraan</label>
                    <textarea class="form-control" id="alamat" rows="3" name="alamat" required></textarea>
                </div>
                <div class="form-group col-md-6">
                    <label for="bahan-bakar">Bahan Bakar</label>
                    <input type="text" class="form-control" id="bahan-bakar" name="bahanBakar" required>
                </div>
            </div>
            <div class="mt-2">
                <button type="submit" class="btn btn-primary">Simpan</button>
                <a class="btn btn-dark" asp-controller="Kendaraan" asp-action="Index">Kembali</a>
            </div>
        </form>
    </div>
</div>


@section Scripts{

    <script>

        $('#form-add').submit((e) => {
            e.preventDefault();
            const { noReg, thnPembuatan, namaPemilik, kapasitas, merk, warna, alamat, bahanBakar } = e.target;
            $.ajax({
                method: "POST",
                url: "/api/Kendaraan/PostKendaraan",
                data: {
                    noRegistrasi: noReg.value,
                    namaPemilik: namaPemilik.value,
                    alamat: alamat.value,
                    merk: merk.value,
                    tahunPembuatan: thnPembuatan.value,
                    kapasitas: kapasitas.value,
                    warna: warna.value,
                    bahanBakar: bahanBakar.value,
                },
                success: function (respon) {
                    alert(`Data Berhasil Ditambahkan`);
                    e.target.reset();
                },
                error: function (err) {
                    alert("Error Server!");
                }
            })
            
        })

        function isNumber(evt) {
            evt = (evt) ? evt : window.event;
            var charCode = (evt.which) ? evt.which : evt.keyCode;
            if (charCode > 31 && (charCode < 48 || charCode > 57)) {
                return false;
            }
            return true;
        }

    </script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DataKendaraan</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
</head>
<body>
    @*<header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DataKendaraan</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DataKendaraan - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>